/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}", "./pages/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f4',
        'surface-dim': '#dbdad5',
        'surface-bright': '#fbf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ee',
        'surface-container': '#f0eee9',
        'surface-container-high': '#eae8e3',
        'surface-container-highest': '#e4e2dd',
        'on-surface': '#1b1c19',
        'on-surface-variant': '#52443d',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f1ec',
        outline: '#84746c',
        'outline-variant': '#d6c3b9',
        primary: '#724428',
        'on-primary': '#ffffff',
        'primary-container': '#8e5b3e',
        'on-primary-container': '#ffe1d2',
        'inverse-primary': '#f9b895',
        secondary: '#53643a',
        'on-secondary': '#ffffff',
        'secondary-container': '#d6eab5',
        'on-secondary-container': '#596a40',
        tertiary: '#624a33',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#7c6249',
        'on-tertiary-container': '#ffe1c6',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fbf9f4',
        'on-background': '#1b1c19',
      },
      spacing: {
        base: '4px',
        xs: '8px',
        sm: '16px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        gutter: '20px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      fontFamily: {
        jakarta: ['var(--font-jakarta)', 'sans-serif'],
        inter: ['var(--font-inter)', 'sans-serif'],
        headline: ['var(--font-jakarta)', 'sans-serif'],
        body: ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', '56px'],
        h1: ['36px', '44px'],
        h2: ['28px', '36px'],
        h3: ['24px', '32px'],
        lg: ['18px', '28px'],
        base: ['16px', '24px'],
        sm: ['14px', '20px'],
        caption: ['12px', '16px'],
      },
    },
  },
  plugins: [],
};
