export const API = {
    AUTH: {
        REGISTER: "/api/auth/register",
        VERIFY_EMAIL: "/api/auth/verify-email",
        LOGIN: "/api/auth/login",
        WHOAMI: "/api/auth/whoami",
        UPDATEPROFILE: "/api/auth/update-profile",
        FORGOT_PASSWORD: "/api/auth/password-reset/request",
        RESET_PASSWORD: (token: string) => `/api/auth/reset-password/${token}`,
        RESET_PASSWORD_OTP: "/api/auth/password-reset/confirm",
        GOOGLE: "/api/auth/google",
        EXISTS: "/api/auth/exists",
        MFA_VERIFY_LOGIN: "/api/auth/mfa/verify-login",
    },
    LISTINGS: {
        LIST: "/api/listings",
        SEARCH: "/api/listings/search/query",
        GET: (id: string) => `/api/listings/${id}`,
        CREATE: "/api/listings",
        UPLOAD_IMAGE: "/api/listings/upload",
        UPDATE: (id: string) => `/api/listings/${id}`,
        DELETE: (id: string) => `/api/listings/${id}`,
        MY: "/api/listings/user/my-listings",
        SOLD: (id: string) => `/api/listings/${id}/sold`,
    },
    ORDERS: {
        LIST: "/api/orders",
        CREATE: "/api/orders",
        GET: (id: string) => `/api/orders/${id}`,
        ACCEPT: (id: string) => `/api/orders/${id}/accept`,
        DECLINE: (id: string) => `/api/orders/${id}/decline`,
        COMPLETE: (id: string) => `/api/orders/${id}/complete`,
    },
    TRANSACTIONS: {
        BY_ORDER: (orderId: string) => `/api/transactions/order/${orderId}`,
        CONFIRM_DELIVERY: (transactionId: string) => `/api/transactions/${transactionId}/confirm-delivery`,
        CONFIRM_HANDOVER: (transactionId: string) => `/api/transactions/${transactionId}/confirm-handover`,
    },
    PROFILES: {
        ME: "/api/profiles/me",
        USER: (userId: string) => `/api/profiles/user/${userId}`,
        SELLER_STATS: (userId: string) => `/api/profiles/seller/${userId}/stats`,
    },
    REVIEWS: {
        LIST: "/api/reviews",
        CREATE: "/api/reviews",
        MY: "/api/reviews/my",
        GET: (id: string) => `/api/reviews/${id}`,
        UPDATE: (id: string) => `/api/reviews/${id}`,
        DELETE: (id: string) => `/api/reviews/${id}`,
    },
    ADMIN: {
        USER: {
            GET_ALL: "/api/admin/users",
            GET_ONE: (id: string) => `/api/admin/users/${id}`,
            CREATE: "/api/admin/users",
            UPDATE: (id: string) => `/api/admin/users/${id}`,
            DELETE: (id: string) => `/api/admin/users/${id}`,
        },
    },
};